### ISSUE TITLE
Customize email templates for Chameleon

### ISSUE THREAD

**Issue by priteau** [ChameleonCloud/portal#31]
When migrating an existing FutureGrid project to Chameleon, the notification email sent to the user has TACC branding rather than Chameleon:

Dear Pierre Riteau,

Your request, submitted on Tuesday, December 02, 2014, for an allocation on the following TACC resource(s) has been received. The request will be reviewed by the TACC allocations committee. You should receive notification of the status of your request on or before Wednesday, December 31, 2014.

Project: FG-224
Resource: Chameleon
SUs: 1

Please submit any questions you may have via the TACC Consulting System: 

https://portal.tacc.utexas.edu/consulting

Thanks,
TACC Accounting Staff

**Comment by mrhanlon** [comment]
Templates are in place.
